################################################################
# Global configuration
################################################################
debug = false
logLevel = "INFO"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
# defaultEntryPoints = ["http", "https"]
defaultEntryPoints = ["https"] 
################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
[entryPoints]
    [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [entryPoints.traefik]
      address = ":8080"
      [entryPoints.traefik.auth.basic]
      users = ["###BASIC_AUTH###"]
    #  [entryPoints.http.redirect]
    #  entryPoint = "https"
    # [entryPoints.https]
    # address = ":443"

# [retry]

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]

  # Name of the related entry point
  entryPoint = "traefik"

  # Enabled Dashboard
  dashboard = true

################################################################
# Ping configuration
################################################################

# Enable ping
# [ping]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

################################################################
# DYNAMIC ZONE
################################################################
